name       : gstreamer-1.0-libav
version    : 1.12.3
release    : 9
source     :
    - https://gstreamer.freedesktop.org/src/gst-libav/gst-libav-1.12.3.tar.xz : 015ef8cab6f7fb87c8fb42642486423eff3b6e6a6bccdcd6a189f436a3619650
license    : LGPL-2.0
component  : multimedia.gstreamer
summary    : GStreamer libav based plugin
description: |
    GStreamer libav based plugin providing H264, AVI support, amongst others
builddeps  :
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(libass)
    - pkgconfig(orc-0.4)
    - bzip2-devel
    - yasm
setup      : |
    %configure --disable-static \
               --enable-shared \
               --with-package-name="GStreamer Libav Plugins ${version} Solus" \
               --with-package-origin="https://solus-project.com"
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
