name       : gstreamer-1.0-libav
version    : 1.16.0
release    : 18
source     :
    - https://gstreamer.freedesktop.org/src/gst-libav/gst-libav-1.16.0.tar.xz : dfac119043a9cfdcacd7acde77f674ab172cf2537b5812be52f49e9cddc53d9a
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : multimedia.gstreamer
summary    : GStreamer libav based plugin
description: |
    GStreamer libav based plugin providing H264, AVI support, amongst others
builddeps  :
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(libass)
    - pkgconfig(libavcodec)
    - pkgconfig(orc-0.4)
    - bzip2-devel
    - yasm
setup      : |
    %configure --disable-static \
               --with-package-name="GStreamer Libav Plugins ${version} Solus" \
               --with-package-origin="https://getsol.us"
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
