name       : gstreamer-1.0-libav
version    : 1.22.4
release    : 26
source     :
    - https://gstreamer.freedesktop.org/src/gst-libav/gst-libav-1.22.4.tar.xz : 9a751bc740de768e791c37a95f0a924c6a41d12fd7f37f54ce6a4e834be122d3
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : multimedia.gstreamer
summary    : GStreamer libav based plugin
description: |
    GStreamer libav based plugin providing H264, AVI support, amongst others
builddeps  :
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(libass)
    - pkgconfig(libavcodec)
    - pkgconfig(orc-0.4)
    - bzip2-devel
    - yasm
setup      : |
    %meson_configure -D package-name="GStreamer Libav Plugins ${version} Solus" \
        -D package-origin="https://getsol.us" 
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check || :
