name       : gstreamer-1.0-libav
version    : 1.8.2
release    : 7
source     :
    - https://gstreamer.freedesktop.org/src/gst-libav/gst-libav-1.8.2.tar.xz : b5f3c7a27b39b5f5c2f0bfd546b0c655020faf6b38d27b64b346c43e5ebf687a
license    :
    - LGPL-2.0
summary    : GStreamer libav based plugin
builddeps  :
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(orc-0.4)
    - pkgconfig(libass)
    - yasm
description: |
    GStreamer libav based plugin providing H264, AVI support, amongst others
setup      : |
    %configure --disable-static \
               --with-package-name="GStreamer Libav Plugins 1.8.2 Solus" \
               --with-package-origin="https://solus-project.com"
build      : |
    %make
install    : |
    %make_install
