name       : gstreamer-1.0-libav
version    : 1.20.3
release    : 24
source     :
    - https://gstreamer.freedesktop.org/src/gst-libav/gst-libav-1.20.3.tar.xz : 3fedd10560fcdfaa1b6462cbf79a38c4e7b57d7f390359393fc0cef6dbf27dfe
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : multimedia.gstreamer
summary    : GStreamer libav based plugin
description: |
    GStreamer libav based plugin providing H264, AVI support, amongst others
builddeps  :
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(libass)
    - pkgconfig(libavcodec)
    - pkgconfig(orc-0.4)
    - bzip2-devel
    - yasm
setup      : |
    %meson_configure -D package-name="GStreamer Libav Plugins ${version} Solus" \
        -D package-origin="https://getsol.us" 
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check || :
