name       : gstreamer-1.0-libav
version    : 1.10.4
release    : 8
source     :
    - https://gstreamer.freedesktop.org/src/gst-libav/gst-libav-1.10.4.tar.xz : 6ca0feca75e3d48315e07f20ec37cf6260ed1e9dde58df355febd5016246268b
license    :
    - LGPL-2.0
summary    : GStreamer libav based plugin
component  : multimedia.gstreamer
builddeps  :
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(orc-0.4)
    - pkgconfig(libass)
    - yasm
description: |
    GStreamer libav based plugin providing H264, AVI support, amongst others
setup      : |
    %configure --disable-static \
               --with-package-name="GStreamer Libav Plugins 1.10.4 Solus" \
               --with-package-origin="https://solus-project.com"
build      : |
    %make
install    : |
    %make_install
