name        : gstreamer-1.0-libav
version     : 1.6.2
release     : 6
source     :
    - http://gstreamer.freedesktop.org/src/gst-libav/gst-libav-1.6.2.tar.xz : 2597acc00171006d49f0d300440a87df51b113d557466e532153abc740db3469
license     :
    - LGPL-2.0
summary     : GStreamer libav based plugin
builddeps   :
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(orc-0.4)
    - pkgconfig(libass)
    - yasm
description : |
    GStreamer libav based plugin providing H264, AVI support, amongst others
setup      : |
    %configure --disable-static \
               --with-package-name="GStreamer Libav Plugins 1.6.2 Solus" \
               --with-package-origin="https://solus-project.com"
build      : |
    %make
install    : |
    %make_install
