name        : gstreamer-1.0-libav
version     : 1.6.1
release     : 5
source     :
    - http://gstreamer.freedesktop.org/src/gst-libav/gst-libav-1.6.1.tar.xz : 24d5e8e8b8c825af1a19aa80a27aba268ec383c8133fd4ef66e0e572ff6137a9
license     :
    - LGPL-2.0
summary     : GStreamer libav based plugin
builddeps   :
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(orc-0.4)
    - pkgconfig(libass)
    - yasm
description : |
    GStreamer libav based plugin providing H264, AVI support, amongst others
setup      : |
    %configure --disable-static \
               --with-package-name="GStreamer Libav Plugins 1.4.5 Solus" \
               --with-package-origin="https://solus-project.com"
build      : |
    %make
install    : |
    %make_install
