name       : gstreamer-1.0-libav
version    : 1.18.4
release    : 22
source     :
    - https://gstreamer.freedesktop.org/src/gst-libav/gst-libav-1.18.4.tar.xz : 344a463badca216c2cef6ee36f9510c190862bdee48dc4591c0a430df7e8c396
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : multimedia.gstreamer
summary    : GStreamer libav based plugin
description: |
    GStreamer libav based plugin providing H264, AVI support, amongst others
builddeps  :
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(libass)
    - pkgconfig(libavcodec)
    - pkgconfig(orc-0.4)
    - bzip2-devel
    - yasm
setup      : |
    %meson_configure -D package-name="GStreamer Libav Plugins ${version} Solus" \
        -D package-origin="https://getsol.us" \
        -D gobject-cast-checks=disabled \
        -D glib-asserts=disabled \
        -D glib-checks=disabled
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check || :
